use_frameworks!

platform :ios, '12.0'

target 'PushedMessagingiOSLibrary_Example' do
  pod 'PushedMessagingiOSLibrary', :path => '../'

  target 'PushedMessagingiOSLibrary_Tests' do
    inherit! :search_paths

    
  end
end
